import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// importing useState and useEffect
import { useState } from "react";



export default function Home() {
  const [counter, setCounter] = useState(0);
  return (
    <div className={styles.container}>
      <Head>
        <title>Testing Co-pilot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* A buttong with plus sign on it */}
      <button onClick={() => setCounter(counter + 1)}>Hello </button>
      {/* Display counter */}
      <p>You have clicked me {counter} times.</p>

    </div>
  );
}
